#!/usr/bin/env perl

use strict;
use warnings;

use Cwd qw/abs_path/;
use File::Basename qw/dirname/;
use File::Path qw/make_path/;
use File::Slurp qw/read_file write_file/;
use File::Spec::Functions;
use above 'UR';

my $mydir = abs_path(dirname($0));
my $output_file = catfile($mydir, "generated", "documentation.html");
make_path(dirname($output_file));
my $pod_file = catfile($mydir, "..", "doc", "joinx.pod");
my $pod = read_file($pod_file);
my @section = UR::Doc::Section->create(content => $pod, format => 'pod');
my $writer = UR::Doc::Writer::Html->create(title => '', sections => \@section);
my $html = $writer->render;
write_file($output_file, $html);
