#!/bin/bash

verstr=`git describe --tags 2> /dev/null`

MAJOR=0
MINOR=0
PATCH=0
VERS=0
case $verstr in
    v[0-9]*)
        VERS=${verstr#v*}
        VERS=${VERS%%-*}
        MAJOR=`echo $VERS | sed 's;^\([0-9]*\)\..*;\1;'`
        MINOR=`echo $VERS | sed 's;^[^.]*\.\([0-9]*\)\..*;\1;'`
        PATCH=`echo $VERS | sed 's;^[^.]*\.[^.]*\.\([0-9]*\).*;\1;'`
        ;;
    *) VERS="0" ;;
esac

case $1 in
    --major) echo $MAJOR ;;
    --minor) echo $MINOR ;;
    --patch) echo $PATCH ;;
    *) echo $VERS ;;
esac
