execute_process(
    COMMAND ${CMAKE_SOURCE_DIR}/buildutil/getversion --major
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE VERSION_MAJOR
    ERROR_VARIABLE VERSION_ERR
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
    COMMAND ${CMAKE_SOURCE_DIR}/buildutil/getversion --minor
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE VERSION_MINOR
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
    COMMAND ${CMAKE_SOURCE_DIR}/buildutil/getversion --patch
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE VERSION_PATCH
    OUTPUT_STRIP_TRAILING_WHITESPACE
)

execute_process(
    COMMAND ${CMAKE_SOURCE_DIR}/buildutil/getversion
    WORKING_DIRECTORY ${CMAKE_SOURCE_DIR}
    OUTPUT_VARIABLE PROJ_VERSION
    OUTPUT_STRIP_TRAILING_WHITESPACE
)


if (NOT (${VERSION_MAJOR} EQUAL "0" AND ${VERSION_MINOR} EQUAL "0"))
    set(EXE_VERSION_SUFFIX "${VERSION_MAJOR}.${VERSION_MINOR}")
endif()
